version: "3.9"

services:
  app:
    build: .
    image: cheebo1/login-app:v12
    container_name: login-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_USER=mongouser
      - MONGO_PASS=mongopassword
      - MONGO_HOST=mongodb 
      - MONGO_PORT=27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    ports:
      - "27017:27017"
